service: selenium-lambda

provider:
  name: aws
  runtime: python3.7
  region: us-east-2

functions:
  main:
    handler: handler.main
    events:
      - httpApi:
          path: /
          method: get

    layers:
      - arn:aws:lambda:us-east-2:464565584485:layer:chromedriver:1
      - arn:aws:lambda:us-east-2:464565584485:layer:selenium:1
